pom.groupId=org.jraf.klibhn
pom.version=1.0.0-SNAPSHOT
pom.description=A HackerNews API client library for Kotlin
pom.vcsUrl=https://github.com/BoD/klibhn
pom.developer=Benoit \'BoD\' Lubek
pom.license=Apache-2.0
java.compatibility=17
kotlin.compatibility=2.2.0
kdoc.projects=:klibhn
