{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibhn",
    "module": "klibhn",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibhn-metadata-1.0.0-SNAPSHOT.jar",
          "url": "klibhn-1.0.0-SNAPSHOT.jar",
          "size": 10475,
          "sha512": "43b4e437f3bb28776a70a5184c238e953096f812051c63e3a9e6b8757f13e40e431500ea47c6dec9cea33091b6c6e755596ae747ef2e31c285269b3a97576002",
          "sha256": "5099d3fa8af4a7c7f912f8e3b797318d7dfb59f0b2c7841135812681947a8549",
          "sha1": "a4f05d60d7f2b3cbf10157cdaf9c13be6aa9e3b9",
          "md5": "938572e4455cc3c29ebd7402ba82c6d1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibhn-kotlin-1.0.0-SNAPSHOT-sources.jar",
          "url": "klibhn-1.0.0-SNAPSHOT-sources.jar",
          "size": 10207,
          "sha512": "1c550de0fe521917d60685c096063430b39e7f9a60f07f20485dea49e3f7853d023fa15bd39bbd5143bc61a3095b13aba4d36a2dfb4ae1a802ad883502d5f560",
          "sha256": "6ebcd907092e549389fe0b49c2a3978325626c9ba5cd9352d75cbabdd68ba064",
          "sha1": "70e696ffa5ce5ab061cbba1d18ef4c5a135144f1",
          "md5": "0099fd570ab285749b757fab9befab10"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibhn-jvm/1.0.0-SNAPSHOT/klibhn-jvm-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibhn",
        "module": "klibhn-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibhn-jvm/1.0.0-SNAPSHOT/klibhn-jvm-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibhn",
        "module": "klibhn-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibhn-jvm/1.0.0-SNAPSHOT/klibhn-jvm-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibhn",
        "module": "klibhn-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibhn-macosarm64/1.0.0-SNAPSHOT/klibhn-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibhn",
        "module": "klibhn-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibhn-macosarm64/1.0.0-SNAPSHOT/klibhn-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibhn",
        "module": "klibhn-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibhn-macosarm64/1.0.0-SNAPSHOT/klibhn-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibhn",
        "module": "klibhn-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
