{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibhn/1.0.0-SNAPSHOT/klibhn-1.0.0-SNAPSHOT.module",
    "group": "org.jraf.klibhn",
    "module": "klibhn",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibhn-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibhn-jvm-1.0.0-SNAPSHOT.jar",
          "size": 71080,
          "sha512": "62ddb8c01ab28f7434a6847467ad16903a6ff5994ab28630095d346b15bde5ea21069ee54b6247a4fb0ea087ca8228d2b5bc08d402ba28823710020cb7c63925",
          "sha256": "55ef67c70f6bdfd9bd5bfaf88f54b4aab8857e5660737c334c5e5887042d62ba",
          "sha1": "2ff7b38ca7c7e7382d4b3e50082f81746f0abfb9",
          "md5": "bc9c8cd6251541b0a2a4fabc61d0f78a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibhn-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibhn-jvm-1.0.0-SNAPSHOT.jar",
          "size": 71080,
          "sha512": "62ddb8c01ab28f7434a6847467ad16903a6ff5994ab28630095d346b15bde5ea21069ee54b6247a4fb0ea087ca8228d2b5bc08d402ba28823710020cb7c63925",
          "sha256": "55ef67c70f6bdfd9bd5bfaf88f54b4aab8857e5660737c334c5e5887042d62ba",
          "sha1": "2ff7b38ca7c7e7382d4b3e50082f81746f0abfb9",
          "md5": "bc9c8cd6251541b0a2a4fabc61d0f78a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibhn-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "klibhn-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 10207,
          "sha512": "1c550de0fe521917d60685c096063430b39e7f9a60f07f20485dea49e3f7853d023fa15bd39bbd5143bc61a3095b13aba4d36a2dfb4ae1a802ad883502d5f560",
          "sha256": "6ebcd907092e549389fe0b49c2a3978325626c9ba5cd9352d75cbabdd68ba064",
          "sha1": "70e696ffa5ce5ab061cbba1d18ef4c5a135144f1",
          "md5": "0099fd570ab285749b757fab9befab10"
        }
      ]
    }
  ]
}
